import {useState} from 'react'; import {Activity,AlertTriangle,BookOpen,Check,ChevronRight,ClipboardList,Clock,FileText,Gauge,History,PackageCheck,Search,ShieldCheck,Sparkles,Wrench} from 'lucide-react'; import type {Diagnosis,Envelope} from './types';
const API=import.meta.env.VITE_API_URL||'';
const tabs=['AI diagnosis','Evidence','Execution trace','Service report'] as const;
export function App(){
 const [symptom,setSymptom]=useState('Pump drive trips on T17 after 20 minutes. Motor housing feels hot and airflow at the cabinet is weak.'); const [data,setData]=useState<Envelope|null>(null); const [active,setActive]=useState<typeof tabs[number]>('AI diagnosis'); const [busy,setBusy]=useState(false); const [approved,setApproved]=useState(false); const [report,setReport]=useState<any>(null); const [error,setError]=useState('');
 async function run(){setBusy(true);setError('');setReport(null);try{const r=await fetch(`${API}/api/diagnose`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'AX-200-P17',symptom,observations:['Ambient 32 C','Last filter service 7 months ago']})});if(!r.ok)throw new Error(`Diagnosis request failed (${r.status})`);setData(await r.json());setActive('AI diagnosis')}catch(e){setError(e instanceof Error?e.message:'Diagnosis request failed')}finally{setBusy(false)}}
 async function generate(){if(!data)return;setError('');try{const r=await fetch(`${API}/api/reports`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({diagnosis:data.diagnosis,approval:{approved:true,technician:'Alex Morgan',notes:'Evidence reviewed'}})});if(!r.ok)throw new Error(`Report request failed (${r.status})`);setReport(await r.json());setActive('Service report')}catch(e){setError(e instanceof Error?e.message:'Report request failed')}}
 return <div className="shell"><aside><div className="brand"><span><Wrench size={19}/></span><b>FieldFix</b><em>AI</em></div><div className="site">NORTH PLANT <small>▾</small></div><nav><a className="on"><Activity/>Active cases <i>3</i></a><a><ClipboardList/>Work orders</a><a><PackageCheck/>Assets</a><a><BookOpen/>Knowledge</a></nav><div className="bottom"><div className="online"><i/> System operational</div><div className="user"><div>AM</div><span><b>Alex Morgan</b><small>Field engineer</small></span></div></div></aside>
 <main><header><div><small>ACTIVE CASE / FF-2026-084</small><h1>Intermittent thermal trip</h1></div><span className="priority"><AlertTriangle size={15}/> Priority: High</span><button className="ghost">•••</button></header>
 <section className="assetbar"><div><small>ASSET</small><b>AX-200 Pump Drive · P-17</b></div><div><small>LOCATION</small><b>Line 4 · Mixing</b></div><div><small>DOWNTIME</small><b className="red">00:47:22</b></div><div><small>ASSIGNEE</small><b>Alex Morgan</b></div></section>
 <div className="workspace"><section className="case"><div className="sectiontitle"><span><Wrench/>Current fault case</span><label>IN PROGRESS</label></div><label className="field">FAULT DESCRIPTION<textarea value={symptom} onChange={e=>setSymptom(e.target.value)}/></label><div className="signals"><span><Gauge/> Ambient <b>32°C</b></span><span><History/> Last service <b>7 mo ago</b></span></div><button className="run" onClick={run} disabled={busy}><Sparkles size={18}/>{busy?'Analyzing evidence…':'Run AI diagnosis'}<ChevronRight size={18}/></button>{error&&<div className="error" role="alert"><AlertTriangle size={16}/>{error}. Check that the API is running and retry.</div>}<div className="safety"><ShieldCheck/><span><b>Safety boundary</b>AI recommendations require technician verification and approval.</span></div></section>
 <section className="result"><div className="tabs">{tabs.map(t=><button key={t} className={active===t?'active':''} onClick={()=>setActive(t)}>{t}{t==='Evidence'&&data?<i>{data.diagnosis.evidence.length}</i>:''}</button>)}</div>{!data?<Empty/>:<Content active={active} data={data} approved={approved} setApproved={setApproved} generate={generate} report={report}/>}</section></div></main></div>}
function Empty(){return <div className="empty"><div><Search/></div><h2>Ready to investigate</h2><p>Run a diagnosis to retrieve manuals and past work orders, then build a grounded repair plan.</p></div>}
function Content({active,data,approved,setApproved,generate,report}:{active:string;data:Envelope;approved:boolean;setApproved:(v:boolean)=>void;generate:()=>void;report:any}){const d:Diagnosis=data.diagnosis;if(active==='Evidence')return <div className="pane"><h2>Retrieved evidence</h2><p className="muted">Only these records may support diagnosis conclusions.</p>{d.evidence.map(e=><article className="evidence" key={e.id}><div><span className={e.source_type}>{e.source_type==='manual'?'MANUAL':'WORK ORDER'}</span><b>{e.id}</b><em>{Math.round(e.score*100)}% match</em></div><h3>{e.title}</h3><small>{e.locator}</small><p>“{e.excerpt}”</p></article>)}</div>;
if(active==='Execution trace')return <div className="pane"><h2>Agent execution trace</h2><div className="telemetry"><span><Clock/>Latency<b>{data.latency_ms} ms</b></span><span><Sparkles/>Mode<b>{data.mode.replace('_',' ')}</b></span><span><Gauge/>Est. cost<b>${data.estimated_cost_usd.toFixed(4)}</b></span></div><div className="timeline">{data.trace.map((t,i)=><div key={`${t.step}-${i}`}><i><Check/></i><span><b>{i+1}. {t.step}</b><p>{t.detail}</p></span><em>{t.duration_ms} ms</em></div>)}</div></div>;
if(active==='Service report')return <div className="pane"><h2>Structured service report</h2>{report?<pre>{JSON.stringify(report,null,2)}</pre>:<div className="empty small"><FileText/><h3>Approval required</h3><p>Approve the plan to generate an auditable JSON service report.</p></div>}</div>;
return <div className="pane"><div className="answerhead"><span><Sparkles/>AI DIAGNOSIS</span><em>{data.mode==='demo_fallback'?'OFFLINE DEMO':'LIVE MODEL'}</em></div><h2>{d.summary}</h2>{d.root_causes.map((c,i)=><article className="cause" key={c.cause}><div className="rank">{i+1}</div><div><h3>{c.cause}</h3><p>{c.rationale}</p><div className="citations">{c.evidence_ids.map(x=><button key={x}>{x}</button>)}</div></div><strong>{Math.round(c.confidence*100)}<small>%</small></strong></article>)}<div className="twocol"><div><h3>Next diagnostic questions</h3><ol>{d.next_questions.map(q=><li key={q}>{q}</li>)}</ol></div><div><h3>Suggested parts</h3>{d.suggested_parts.map(p=><p className="part" key={p.sku}><PackageCheck/><span><b>{p.name}</b><small>{p.sku} · Qty {p.quantity}</small></span></p>)}</div></div><h3>Repair plan</h3><div className="steps">{d.repair_plan.map(s=><div key={s.order}><i>{s.order}</i><span>{s.instruction}{s.safety_note&&<small>{s.safety_note}</small>}</span></div>)}</div><div className="approval"><div><ShieldCheck/><span><b>Human approval</b><small>Confirm evidence and site safety procedures before work.</small></span></div><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I reviewed and approve this plan</label><button disabled={!approved} onClick={generate}>Generate service report</button></div></div>}
